version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: booking_system_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - booking_db_data:/var/lib/postgresql/data

volumes:
  booking_db_data:
